// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF65w0fis_1DxO1XoHy64RGSVZxv9wNAU',
    appId: '1:1019009831264:web:7c1ff48b43f3c22162ce05',
    messagingSenderId: '1019009831264',
    projectId: 'quittr-22220',
    authDomain: 'quittr-22220.firebaseapp.com',
    storageBucket: 'quittr-22220.firebasestorage.app',
    measurementId: 'G-E8NCQ5YEDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD90xccKsSAbX5nuD3_T7BApxjWF5exZA',
    appId: '1:1019009831264:android:4c061c4607cb384162ce05',
    messagingSenderId: '1019009831264',
    projectId: 'quittr-22220',
    storageBucket: 'quittr-22220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxLtjVThNthSmNlHyOQicv7wtsKjq030',
    appId: '1:1019009831264:ios:81cd310ab4eb061a62ce05',
    messagingSenderId: '1019009831264',
    projectId: 'quittr-22220',
    storageBucket: 'quittr-22220.firebasestorage.app',
    iosBundleId: 'quit.addition.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFxLtjVThNthSmNlHyOQicv7wtsKjq030',
    appId: '1:1019009831264:ios:5674a17930c673a662ce05',
    messagingSenderId: '1019009831264',
    projectId: 'quittr-22220',
    storageBucket: 'quittr-22220.firebasestorage.app',
    iosBundleId: 'quit.addition.app.quittr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF65w0fis_1DxO1XoHy64RGSVZxv9wNAU',
    appId: '1:1019009831264:web:679504a858a09c8462ce05',
    messagingSenderId: '1019009831264',
    projectId: 'quittr-22220',
    authDomain: 'quittr-22220.firebaseapp.com',
    storageBucket: 'quittr-22220.firebasestorage.app',
    measurementId: 'G-92D960CLJK',
  );
}
